# Github Actions YML file

name: 'Github Project to Markdown'
description: 'Write Github Projects as a Markdown File'

branding:
  icon: file-text
  color: black

inputs:
  github_token:
    description: The Github token.
    required: true
  markdown_path:
    required: true
    description: The location at which a markdown file will be created.
  github_repository:
    description: The Github Repository to retrieve the project from.
    required: true
  project_number:
    description: The Github Project to retrieve.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --github-token=${{ inputs.github_token }}
    - --output-file=${{ inputs.markdown_path }}
    - ${{ inputs.github_repository }}
    - ${{ inputs.project_number }}
